/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MowayJava */

#ifndef _Included_MowayJava
#define _Included_MowayJava
#ifdef __cplusplus
extern "C" {
#endif
#undef MowayJava_MW_OPEN_SHARE_MODE
#define MowayJava_MW_OPEN_SHARE_MODE 0L
#undef MowayJava_MW_OPEN_EXCLUSIVE_MODE
#define MowayJava_MW_OPEN_EXCLUSIVE_MODE 1L
#undef MowayJava_MW_ALG_TYPE_AES
#define MowayJava_MW_ALG_TYPE_AES 0L
#undef MowayJava_MW_ALG_TYPE_DES
#define MowayJava_MW_ALG_TYPE_DES 1L
#undef MowayJava_MW_ALG_TYPE_TDES
#define MowayJava_MW_ALG_TYPE_TDES 2L
#undef MowayJava_MW_ALG_TYPE_ECC
#define MowayJava_MW_ALG_TYPE_ECC 16L
#undef MowayJava_MW_ALG_TYPE_RSA
#define MowayJava_MW_ALG_TYPE_RSA 17L
#undef MowayJava_MW_SYM_ALGO_MODE_ECB
#define MowayJava_MW_SYM_ALGO_MODE_ECB 0L
#undef MowayJava_MW_SYM_ALGO_MODE_CBC
#define MowayJava_MW_SYM_ALGO_MODE_CBC 1L
#undef MowayJava_MW_FILE_TYPE_BINARY
#define MowayJava_MW_FILE_TYPE_BINARY 0L
#undef MowayJava_MW_FILE_TYPE_KEY
#define MowayJava_MW_FILE_TYPE_KEY 2L
#undef MowayJava_MW_FILE_PRIV_TYPE_USE
#define MowayJava_MW_FILE_PRIV_TYPE_USE 0L
#undef MowayJava_MW_FILE_PRIV_TYPE_READ
#define MowayJava_MW_FILE_PRIV_TYPE_READ 1L
#undef MowayJava_MW_FILE_PRIV_TYPE_READ_WRITE
#define MowayJava_MW_FILE_PRIV_TYPE_READ_WRITE 2L
#undef MowayJava_MW_GET_INFO_ITEM_PID
#define MowayJava_MW_GET_INFO_ITEM_PID 0L
#undef MowayJava_MW_GET_INFO_ITEM_SN
#define MowayJava_MW_GET_INFO_ITEM_SN 1L
#undef MowayJava_MW_GET_INFO_ITEM_PRODUCE_DATE
#define MowayJava_MW_GET_INFO_ITEM_PRODUCE_DATE 2L
#undef MowayJava_MW_GET_INFO_ITEM_ALL_CAPACITY
#define MowayJava_MW_GET_INFO_ITEM_ALL_CAPACITY 3L
#undef MowayJava_MW_GET_INFO_ITEM_FREE_CAPACITY
#define MowayJava_MW_GET_INFO_ITEM_FREE_CAPACITY 4L
#undef MowayJava_MW_GET_INFO_ITEM_VERSION
#define MowayJava_MW_GET_INFO_ITEM_VERSION 5L
#undef MowayJava_MW_GET_INFO_ITEM_SHELL_SN
#define MowayJava_MW_GET_INFO_ITEM_SHELL_SN 6L
#undef MowayJava_MW_GET_INFO_ITEM_STATUS
#define MowayJava_MW_GET_INFO_ITEM_STATUS 7L
#undef MowayJava_MW_GET_INFO_ITEM_UPDATE_CODE
#define MowayJava_MW_GET_INFO_ITEM_UPDATE_CODE 8L
#undef MowayJava_MW_GET_INFO_ITEM_UPDATE_CTRL_CODE
#define MowayJava_MW_GET_INFO_ITEM_UPDATE_CTRL_CODE 9L
#undef MowayJava_MW_GET_INFO_ITEM_ALL
#define MowayJava_MW_GET_INFO_ITEM_ALL 255L
#undef MowayJava_MW_STATUS_FLAG_DEFAULT
#define MowayJava_MW_STATUS_FLAG_DEFAULT 0L
#undef MowayJava_MW_STATUS_FLAG_PID
#define MowayJava_MW_STATUS_FLAG_PID 1L
#undef MowayJava_MW_STATUS_FLAG_PIN
#define MowayJava_MW_STATUS_FLAG_PIN 2L
#undef MowayJava_MW_CTRL_CODE_ITEM_RESET
#define MowayJava_MW_CTRL_CODE_ITEM_RESET 0L
#undef MowayJava_MW_CTRL_CODE_ITEM_LED
#define MowayJava_MW_CTRL_CODE_ITEM_LED 1L
#undef MowayJava_MW_PIN_TYPE_NONE
#define MowayJava_MW_PIN_TYPE_NONE 0L
#undef MowayJava_MW_PIN_TYPE_USER
#define MowayJava_MW_PIN_TYPE_USER 1L
#undef MowayJava_MW_PIN_TYPE_DEVELOPER
#define MowayJava_MW_PIN_TYPE_DEVELOPER 2L
#undef MowayJava_MW_PIN_LENGTH_USER
#define MowayJava_MW_PIN_LENGTH_USER 8L
#undef MowayJava_MW_PIN_LENGTH_DEVELOPER
#define MowayJava_MW_PIN_LENGTH_DEVELOPER 24L
#undef MowayJava_MW_RSA_MODE_NORMAL
#define MowayJava_MW_RSA_MODE_NORMAL 0L
#undef MowayJava_MW_RSA_MODE_PKCS1_V1_5
#define MowayJava_MW_RSA_MODE_PKCS1_V1_5 1L
#undef MowayJava_MW_RSA_1024_BYTE_SIZE
#define MowayJava_MW_RSA_1024_BYTE_SIZE 128L
#undef MowayJava_MW_RSA_2048_BYTE_SIZE
#define MowayJava_MW_RSA_2048_BYTE_SIZE 256L
#undef MowayJava_MW_HASH_ALGO_MD5
#define MowayJava_MW_HASH_ALGO_MD5 0L
#undef MowayJava_MW_HASH_ALGO_SHA1
#define MowayJava_MW_HASH_ALGO_SHA1 1L
#undef MowayJava_MW_HASH_ALGO_SHA256
#define MowayJava_MW_HASH_ALGO_SHA256 2L
#undef MowayJava_MW_HASH_ALGO_NONE
#define MowayJava_MW_HASH_ALGO_NONE 255L
#undef MowayJava_MW_UPDATE_FILE_COUNT_MAX
#define MowayJava_MW_UPDATE_FILE_COUNT_MAX 50L
#undef MowayJava_MW_UPDATE_MOD_FLAG_DELETE
#define MowayJava_MW_UPDATE_MOD_FLAG_DELETE 2L
#undef MowayJava_MW_UPDATE_MOD_FLAG_WRITE
#define MowayJava_MW_UPDATE_MOD_FLAG_WRITE 16L
#undef MowayJava_MW_UPDATE_MOD_FLAG_CREATE
#define MowayJava_MW_UPDATE_MOD_FLAG_CREATE 32L
#undef MowayJava_MW_LANGUAGE_ID_DEFAULT
#define MowayJava_MW_LANGUAGE_ID_DEFAULT 0L
#undef MowayJava_MW_LANGUAGE_ID_CH
#define MowayJava_MW_LANGUAGE_ID_CH 1L
#undef MowayJava_MW_LANGUAGE_ID_EN
#define MowayJava_MW_LANGUAGE_ID_EN 2L
#undef MowayJava_MW_PATH_LEN
#define MowayJava_MW_PATH_LEN 1024L
#undef MowayJava_MW_SYM_ALG_IV_LENGTH
#define MowayJava_MW_SYM_ALG_IV_LENGTH 16L
#undef MowayJava_MW_SN_LENGTH
#define MowayJava_MW_SN_LENGTH 16L
#undef MowayJava_MW_FILE_NAME_LENGTH_MAX
#define MowayJava_MW_FILE_NAME_LENGTH_MAX 16L
#undef MowayJava_MW_HMAC_MD5_DIGEST_LENGTH
#define MowayJava_MW_HMAC_MD5_DIGEST_LENGTH 16L
#undef MowayJava_MW_HMAC_SHA1_DIGEST_LENGTH
#define MowayJava_MW_HMAC_SHA1_DIGEST_LENGTH 20L
#undef MowayJava_MW_HMAC_SHA256_DIGEST_LENGTH
#define MowayJava_MW_HMAC_SHA256_DIGEST_LENGTH 32L
#undef MowayJava_MW_INPUT_DATA_LENGTH_MAX
#define MowayJava_MW_INPUT_DATA_LENGTH_MAX 1900L
#undef MowayJava_MW_SEED_LENGTH_MAX
#define MowayJava_MW_SEED_LENGTH_MAX 32L
#undef MowayJava_MW_SEED_LENGTH_MIN
#define MowayJava_MW_SEED_LENGTH_MIN 4L
#undef MowayJava_MW_ENUM_DEVICE_MAX_COUNT
#define MowayJava_MW_ENUM_DEVICE_MAX_COUNT 128L
#undef MowayJava_MW_SUCCESS
#define MowayJava_MW_SUCCESS 0L
#undef MowayJava_MW_ERROR_INVALID_HANDLE
#define MowayJava_MW_ERROR_INVALID_HANDLE 1L
#undef MowayJava_MW_ERROR_INVALID_PARAMETER
#define MowayJava_MW_ERROR_INVALID_PARAMETER 2L
#undef MowayJava_MW_ERROR_NOT_ENOUGH_MEMORY
#define MowayJava_MW_ERROR_NOT_ENOUGH_MEMORY 3L
#undef MowayJava_MW_ERROR_NO_DEVICE
#define MowayJava_MW_ERROR_NO_DEVICE 4L
#undef MowayJava_MW_ERROR_TIMEOUT
#define MowayJava_MW_ERROR_TIMEOUT 5L
#undef MowayJava_MW_ERROR_UNSUPPORTED_FLAG
#define MowayJava_MW_ERROR_UNSUPPORTED_FLAG 6L
#undef MowayJava_MW_ERROR_INSUFFICIENT_BUFFER
#define MowayJava_MW_ERROR_INSUFFICIENT_BUFFER 7L
#undef MowayJava_MW_ERROR_EXCHG_MEMORY_NOT_FOUND
#define MowayJava_MW_ERROR_EXCHG_MEMORY_NOT_FOUND 8L
#undef MowayJava_MW_ERROR_SYSTEM_FILE_NOT_FOUND
#define MowayJava_MW_ERROR_SYSTEM_FILE_NOT_FOUND 9L
#undef MowayJava_MW_ERROR_SYSTEM_FILE_INVALID_ACCESS
#define MowayJava_MW_ERROR_SYSTEM_FILE_INVALID_ACCESS 10L
#undef MowayJava_MW_ERROR_FILE_EXISTS
#define MowayJava_MW_ERROR_FILE_EXISTS 11L
#undef MowayJava_MW_ERROR_FILE_NOT_FOUND
#define MowayJava_MW_ERROR_FILE_NOT_FOUND 12L
#undef MowayJava_MW_ERROR_NO_PRIVILEGE
#define MowayJava_MW_ERROR_NO_PRIVILEGE 13L
#undef MowayJava_MW_ERROR_WRONG_PASSWORD
#define MowayJava_MW_ERROR_WRONG_PASSWORD 14L
#undef MowayJava_MW_ERROR_PASSWORD_LOCKED
#define MowayJava_MW_ERROR_PASSWORD_LOCKED 15L
#undef MowayJava_MW_ERROR_FUNCTION_NOT_SUPPORTED
#define MowayJava_MW_ERROR_FUNCTION_NOT_SUPPORTED 17L
#undef MowayJava_MW_ERROR_COMMUNICATION
#define MowayJava_MW_ERROR_COMMUNICATION 21L
#undef MowayJava_MW_ERROR_UNSUPPORTED_PASSWORD_TYPE
#define MowayJava_MW_ERROR_UNSUPPORTED_PASSWORD_TYPE 22L
#undef MowayJava_MW_ERROR_WRONG_PASSWORD_LENGTH
#define MowayJava_MW_ERROR_WRONG_PASSWORD_LENGTH 23L
#undef MowayJava_MW_ERROR_ALREADY_EXCLUSIVELY_LOGIN
#define MowayJava_MW_ERROR_ALREADY_EXCLUSIVELY_LOGIN 24L
#undef MowayJava_MW_ERROR_ALREADY_SHARED_LOGIN
#define MowayJava_MW_ERROR_ALREADY_SHARED_LOGIN 25L
#undef MowayJava_MW_ERROR_ALREADY_TEMP_EXCLUSIVELY_USING
#define MowayJava_MW_ERROR_ALREADY_TEMP_EXCLUSIVELY_USING 26L
#undef MowayJava_MW_ERROR_NOT_TEMP_EXCLUSIVELY_USING
#define MowayJava_MW_ERROR_NOT_TEMP_EXCLUSIVELY_USING 27L
#undef MowayJava_MW_ERROR_TOO_MUCH_DATA
#define MowayJava_MW_ERROR_TOO_MUCH_DATA 28L
#undef MowayJava_MW_ERROR_INSUFFICIENT_DEVICE_SPACE
#define MowayJava_MW_ERROR_INSUFFICIENT_DEVICE_SPACE 30L
#undef MowayJava_MW_ERROR_DEVICE_FILESYSTEM_ERROR
#define MowayJava_MW_ERROR_DEVICE_FILESYSTEM_ERROR 31L
#undef MowayJava_MW_ERROR_FILE_OUT_RANGE
#define MowayJava_MW_ERROR_FILE_OUT_RANGE 32L
#undef MowayJava_MW_ERROR_UNSUPPORTED_FILE_TYPE
#define MowayJava_MW_ERROR_UNSUPPORTED_FILE_TYPE 33L
#undef MowayJava_MW_ERROR_FILE_OFFSET_MUST_BE_ZERO
#define MowayJava_MW_ERROR_FILE_OFFSET_MUST_BE_ZERO 34L
#undef MowayJava_MW_ERROR_BAD_EXECUTIVE_FILE_FORMAT
#define MowayJava_MW_ERROR_BAD_EXECUTIVE_FILE_FORMAT 35L
#undef MowayJava_MW_ERROR_OPEN_TOO_MANY_DEVICE_FILES
#define MowayJava_MW_ERROR_OPEN_TOO_MANY_DEVICE_FILES 36L
#undef MowayJava_MW_ERROR_INVALID_DEVICE_FILE_HANDLE
#define MowayJava_MW_ERROR_INVALID_DEVICE_FILE_HANDLE 37L
#undef MowayJava_MW_ERROR_FILE_NOT_FINISHED
#define MowayJava_MW_ERROR_FILE_NOT_FINISHED 38L
#undef MowayJava_MW_ERROR_BAD_FILENAME
#define MowayJava_MW_ERROR_BAD_FILENAME 39L
#undef MowayJava_MW_ERROR_BAD_NAME
#define MowayJava_MW_ERROR_BAD_NAME 40L
#undef MowayJava_MW_ERROR_DEVICE_TIMER
#define MowayJava_MW_ERROR_DEVICE_TIMER 41L
#undef MowayJava_MW_ERROR_NO_EXECUTIVE_FILE_RUNNING
#define MowayJava_MW_ERROR_NO_EXECUTIVE_FILE_RUNNING 42L
#undef MowayJava_MW_ERROR_DEVICE_USER_BUFFER_FULL
#define MowayJava_MW_ERROR_DEVICE_USER_BUFFER_FULL 43L
#undef MowayJava_MW_ERROR_DEVICE_USER_BUFFER_EMPTY
#define MowayJava_MW_ERROR_DEVICE_USER_BUFFER_EMPTY 44L
#undef MowayJava_MW_ERROR_DEVICE_MSG_NOT_REPLIED
#define MowayJava_MW_ERROR_DEVICE_MSG_NOT_REPLIED 45L
#undef MowayJava_MW_ERROR_DEVICE_DUMMY_MSG
#define MowayJava_MW_ERROR_DEVICE_DUMMY_MSG 46L
#undef MowayJava_MW_ERROR_DEVICE_MEMORY_ADDR
#define MowayJava_MW_ERROR_DEVICE_MEMORY_ADDR 47L
#undef MowayJava_MW_ERROR_DEVICE_MEMORY_LENGTH
#define MowayJava_MW_ERROR_DEVICE_MEMORY_LENGTH 48L
#undef MowayJava_MW_ERROR_CONTROL_CODE
#define MowayJava_MW_ERROR_CONTROL_CODE 49L
#undef MowayJava_MW_ERROR_UNKNOW_COMMAND
#define MowayJava_MW_ERROR_UNKNOW_COMMAND 50L
#undef MowayJava_MW_ERROR_INVALID_COMMAND_PARAMETER
#define MowayJava_MW_ERROR_INVALID_COMMAND_PARAMETER 51L
#undef MowayJava_MW_ERROR_COMMAND_DATA_LENGTH
#define MowayJava_MW_ERROR_COMMAND_DATA_LENGTH 52L
#undef MowayJava_MW_ERROR_DEVICE_BUFFER_FULL
#define MowayJava_MW_ERROR_DEVICE_BUFFER_FULL 53L
#undef MowayJava_MW_ERROR_EXECUTIVE_FILE_RUNNING
#define MowayJava_MW_ERROR_EXECUTIVE_FILE_RUNNING 54L
#undef MowayJava_MW_ERROR_NO_DEVICE_MESSAGE
#define MowayJava_MW_ERROR_NO_DEVICE_MESSAGE 55L
#undef MowayJava_MW_ERROR_LOGIN_COUNT
#define MowayJava_MW_ERROR_LOGIN_COUNT 56L
#undef MowayJava_MW_ERROR_KEYEXCHANGE_FAILED
#define MowayJava_MW_ERROR_KEYEXCHANGE_FAILED 57L
#undef MowayJava_MW_ERROR_BAD_COMMUNICATION_KEY
#define MowayJava_MW_ERROR_BAD_COMMUNICATION_KEY 58L
#undef MowayJava_MW_ERROR_BAD_DEVICE_TIME
#define MowayJava_MW_ERROR_BAD_DEVICE_TIME 59L
#undef MowayJava_MW_ERROR_BAD_DEVICE_INFOMATION
#define MowayJava_MW_ERROR_BAD_DEVICE_INFOMATION 60L
#undef MowayJava_MW_ERROR_BAD_COMMAND_SEQUENCE
#define MowayJava_MW_ERROR_BAD_COMMAND_SEQUENCE 61L
#undef MowayJava_MW_ERROR_COMMUNICATION_DATA_LENGTH
#define MowayJava_MW_ERROR_COMMUNICATION_DATA_LENGTH 62L
#undef MowayJava_MW_ERROR_ECC
#define MowayJava_MW_ERROR_ECC 63L
#undef MowayJava_MW_ERROR_BAD_UPDATE_DATA_LENGTH
#define MowayJava_MW_ERROR_BAD_UPDATE_DATA_LENGTH 64L
#undef MowayJava_MW_ERROR_UPDATE_STATE
#define MowayJava_MW_ERROR_UPDATE_STATE 66L
#undef MowayJava_MW_ERROR_UPDATE_KEY_NOT_ENABLE
#define MowayJava_MW_ERROR_UPDATE_KEY_NOT_ENABLE 67L
#undef MowayJava_MW_ERROR_LOCKED_FOREVER
#define MowayJava_MW_ERROR_LOCKED_FOREVER 68L
#undef MowayJava_MW_ERROR_LOCKED_TEMPORARY
#define MowayJava_MW_ERROR_LOCKED_TEMPORARY 69L
#undef MowayJava_MW_ERROR_DEVICE_UNLOCKED
#define MowayJava_MW_ERROR_DEVICE_UNLOCKED 70L
#undef MowayJava_MW_ERROR_DEVICE_FLASH
#define MowayJava_MW_ERROR_DEVICE_FLASH 71L
#undef MowayJava_MW_ERROR_DEVICE_ERROR
#define MowayJava_MW_ERROR_DEVICE_ERROR 72L
#undef MowayJava_MW_ERROR_TOO_MANY_DEVICE
#define MowayJava_MW_ERROR_TOO_MANY_DEVICE 73L
#undef MowayJava_MW_ERROR_DEVICE_NOT_ENOUGH_USER_MEMORY
#define MowayJava_MW_ERROR_DEVICE_NOT_ENOUGH_USER_MEMORY 74L
#undef MowayJava_MW_ERROR_FAKE_DEVICE
#define MowayJava_MW_ERROR_FAKE_DEVICE 75L
#undef MowayJava_MW_ERROR_DEVICE_BLK_OUT_RANGE
#define MowayJava_MW_ERROR_DEVICE_BLK_OUT_RANGE 76L
#undef MowayJava_MW_ERROR_DEVICE_FS_ERR_BAK_ERROR
#define MowayJava_MW_ERROR_DEVICE_FS_ERR_BAK_ERROR 77L
#undef MowayJava_MW_ERROR_DEVICE_TMR_ERR_ADJUST_TIME_TIMEOUT
#define MowayJava_MW_ERROR_DEVICE_TMR_ERR_ADJUST_TIME_TIMEOUT 78L
#undef MowayJava_MW_ERROR_DEVICE_EXCH_ERROR
#define MowayJava_MW_ERROR_DEVICE_EXCH_ERROR 79L
#undef MowayJava_MW_ERROR_DEVICE_AES_ERR
#define MowayJava_MW_ERROR_DEVICE_AES_ERR 80L
#undef MowayJava_MW_ERROR_DEVICE_HASH_ERR_UNSUPPORTED_ALGO
#define MowayJava_MW_ERROR_DEVICE_HASH_ERR_UNSUPPORTED_ALGO 81L
#undef MowayJava_MW_ERROR_DEVICE_BAD_PRIVATE_KEY
#define MowayJava_MW_ERROR_DEVICE_BAD_PRIVATE_KEY 82L
#undef MowayJava_MW_ERROR_DEVICE_BAD_PUBLIC_KEY
#define MowayJava_MW_ERROR_DEVICE_BAD_PUBLIC_KEY 83L
#undef MowayJava_MW_ERROR_DEVICE_BAD_SYMMETRIC_KEY
#define MowayJava_MW_ERROR_DEVICE_BAD_SYMMETRIC_KEY 84L
#undef MowayJava_MW_ERROR_DEVICE_BAD_SIGNATURE
#define MowayJava_MW_ERROR_DEVICE_BAD_SIGNATURE 85L
#undef MowayJava_MW_ERROR_DEVICE_KEY_ERR_BAD_ALGO
#define MowayJava_MW_ERROR_DEVICE_KEY_ERR_BAD_ALGO 86L
#undef MowayJava_MW_ERROR_DEVICE_LOGO_ERR_LOGO
#define MowayJava_MW_ERROR_DEVICE_LOGO_ERR_LOGO 87L
#undef MowayJava_MW_ERROR_EXEC_PARAM_TOO_LONG
#define MowayJava_MW_ERROR_EXEC_PARAM_TOO_LONG 88L
#undef MowayJava_MW_ERROR_OPEN_ERROR
#define MowayJava_MW_ERROR_OPEN_ERROR 89L
#undef MowayJava_MW_ERROR_LOAD_SYS_MODULE_ERROR
#define MowayJava_MW_ERROR_LOAD_SYS_MODULE_ERROR 90L
#undef MowayJava_MW_ERROR_SYS_MODULE_FUNCTION_ERROR
#define MowayJava_MW_ERROR_SYS_MODULE_FUNCTION_ERROR 91L
#undef MowayJava_MW_ERROR_RSA
#define MowayJava_MW_ERROR_RSA 92L
#undef MowayJava_MW_ERROR_KEY
#define MowayJava_MW_ERROR_KEY 93L
#undef MowayJava_MW_ERROR_DEVICE_EXEC_ERR_UNALIGNED_MEM_ADDR
#define MowayJava_MW_ERROR_DEVICE_EXEC_ERR_UNALIGNED_MEM_ADDR 94L
#undef MowayJava_MW_ERROR_DEVICE_EXEC_ERR_STACK_OVERFLOW
#define MowayJava_MW_ERROR_DEVICE_EXEC_ERR_STACK_OVERFLOW 95L
#undef MowayJava_MW_ERROR_DEVELOPER_ID_MISMATCH
#define MowayJava_MW_ERROR_DEVELOPER_ID_MISMATCH 96L
#undef MowayJava_MW_ERROR_LM_GENERAL_ERROR
#define MowayJava_MW_ERROR_LM_GENERAL_ERROR 97L
#undef MowayJava_MW_ERROR_LM_UNSUPPORTED_CERT_TYPE
#define MowayJava_MW_ERROR_LM_UNSUPPORTED_CERT_TYPE 98L
#undef MowayJava_MW_ERROR_LM_UNSUPPORTED_UPDATE_OBJECT_TYPE
#define MowayJava_MW_ERROR_LM_UNSUPPORTED_UPDATE_OBJECT_TYPE 99L
#undef MowayJava_MW_ERROR_LM_UPDATE_PKG_FORMAT_WRONG
#define MowayJava_MW_ERROR_LM_UPDATE_PKG_FORMAT_WRONG 100L
#undef MowayJava_MW_ERROR_CERT
#define MowayJava_MW_ERROR_CERT 101L
#undef MowayJava_MW_ERROR_DEX_NOT_LOADED
#define MowayJava_MW_ERROR_DEX_NOT_LOADED 102L
#undef MowayJava_MW_ERROR_SYSAPP_NOT_FOUND
#define MowayJava_MW_ERROR_SYSAPP_NOT_FOUND 103L
#undef MowayJava_MW_ERROR_UNSUPPORTED_OBJECT_TYPE
#define MowayJava_MW_ERROR_UNSUPPORTED_OBJECT_TYPE 104L
#undef MowayJava_MW_ERROR_UPDATE_BLOCK_LENGTH
#define MowayJava_MW_ERROR_UPDATE_BLOCK_LENGTH 105L
#undef MowayJava_MW_ERROR_UPDATE_SEED_NOT_FOUND
#define MowayJava_MW_ERROR_UPDATE_SEED_NOT_FOUND 106L
#undef MowayJava_MW_ERROR_HEAP
#define MowayJava_MW_ERROR_HEAP 107L
#undef MowayJava_MW_ERROR_DEX_OUT_OF_RANGE
#define MowayJava_MW_ERROR_DEX_OUT_OF_RANGE 108L
#undef MowayJava_MW_ERROR_DEX_TOO_LARGE
#define MowayJava_MW_ERROR_DEX_TOO_LARGE 109L
#undef MowayJava_MW_ERROR_UPDATE_INFO
#define MowayJava_MW_ERROR_UPDATE_INFO 110L
#undef MowayJava_MW_ERROR_DEVICE_STACK_OVERFLOW
#define MowayJava_MW_ERROR_DEVICE_STACK_OVERFLOW 111L
#undef MowayJava_MW_ERROR_COMMUNICATION_CRYPT
#define MowayJava_MW_ERROR_COMMUNICATION_CRYPT 112L
#undef MowayJava_MW_ERROR_BAD_UPDATE_PKG
#define MowayJava_MW_ERROR_BAD_UPDATE_PKG 113L
#undef MowayJava_MW_ERROR_UPDATE_PKG_VERSION_LOW
#define MowayJava_MW_ERROR_UPDATE_PKG_VERSION_LOW 114L
#undef MowayJava_MW_ERROR_UPDATE_OBJECT_TYPE
#define MowayJava_MW_ERROR_UPDATE_OBJECT_TYPE 115L
#undef MowayJava_MW_ERROR_UPDATE_DEVELOPER_ID
#define MowayJava_MW_ERROR_UPDATE_DEVELOPER_ID 116L
#undef MowayJava_MW_ERROR_UPDATE_FILE_TYPE
#define MowayJava_MW_ERROR_UPDATE_FILE_TYPE 117L
#undef MowayJava_MW_ERROR_NO_ADJUST_TIME_REQUEST
#define MowayJava_MW_ERROR_NO_ADJUST_TIME_REQUEST 118L
#undef MowayJava_MW_ERROR_CERT_REVOKED
#define MowayJava_MW_ERROR_CERT_REVOKED 119L
#undef MowayJava_MW_ERROR_WRONG_CERT_SLOT
#define MowayJava_MW_ERROR_WRONG_CERT_SLOT 120L
#undef MowayJava_MW_ERROR_DEVICE_HASH_ERR_NOT_MATCH
#define MowayJava_MW_ERROR_DEVICE_HASH_ERR_NOT_MATCH 121L
#undef MowayJava_MW_ERROR_BAD_RND
#define MowayJava_MW_ERROR_BAD_RND 122L
#undef MowayJava_MW_ERROR_RTC
#define MowayJava_MW_ERROR_RTC 123L
#undef MowayJava_MW_ERROR_RTC_POWER
#define MowayJava_MW_ERROR_RTC_POWER 124L
#undef MowayJava_MW_ERROR_NO_PID_DEVICE
#define MowayJava_MW_ERROR_NO_PID_DEVICE 8193L
#undef MowayJava_MW_ERROR_RET_DATA_FORMAT
#define MowayJava_MW_ERROR_RET_DATA_FORMAT 8194L
#undef MowayJava_MW_ERROR_FILE_NAME_LEN
#define MowayJava_MW_ERROR_FILE_NAME_LEN 8195L
#undef MowayJava_MW_ERROR_BLOCK_DATA
#define MowayJava_MW_ERROR_BLOCK_DATA 8196L
#undef MowayJava_MW_ERROR_FILE_PROPERTY_PARAM
#define MowayJava_MW_ERROR_FILE_PROPERTY_PARAM 8197L
#undef MowayJava_MW_ERROR_FILE_COUNT_MAX
#define MowayJava_MW_ERROR_FILE_COUNT_MAX 8198L
#undef MowayJava_MW_ERROR_MALLOC_MEMORY
#define MowayJava_MW_ERROR_MALLOC_MEMORY 8199L
#undef MowayJava_MW_ERROR_PIN_LENGTH
#define MowayJava_MW_ERROR_PIN_LENGTH 8200L
#undef MowayJava_MW_ERROR_UPDATA_PKG_PID
#define MowayJava_MW_ERROR_UPDATA_PKG_PID 8201L
#undef MowayJava_MW_ERROR_ENTRY_TYPE
#define MowayJava_MW_ERROR_ENTRY_TYPE 40961L
#undef MowayJava_MW_ERROR_ENTRY_FLAG
#define MowayJava_MW_ERROR_ENTRY_FLAG 40962L
#undef MowayJava_MW_ERROR_OPCODE
#define MowayJava_MW_ERROR_OPCODE 40963L
#undef MowayJava_MW_ERROR_PARAM
#define MowayJava_MW_ERROR_PARAM 40964L
#undef MowayJava_MW_ERROR_DATA_LENGTH
#define MowayJava_MW_ERROR_DATA_LENGTH 40965L
#undef MowayJava_MW_ERROR_PIN
#define MowayJava_MW_ERROR_PIN 40966L
#undef MowayJava_MW_ERROR_DEVICE_BLOCK
#define MowayJava_MW_ERROR_DEVICE_BLOCK 40967L
#undef MowayJava_MW_ERROR_PRIVILEGE
#define MowayJava_MW_ERROR_PRIVILEGE 40968L
#undef MowayJava_MW_ERROR_DATA_INFO
#define MowayJava_MW_ERROR_DATA_INFO 40969L
#undef MowayJava_MW_ERROR_HASH_TYPE
#define MowayJava_MW_ERROR_HASH_TYPE 40970L
#undef MowayJava_MW_ERROR_ALG_MODE
#define MowayJava_MW_ERROR_ALG_MODE 40971L
#undef MowayJava_MW_ERROR_INIT_EVT
#define MowayJava_MW_ERROR_INIT_EVT 40972L
#undef MowayJava_MW_ERROR_ALG_TYPE
#define MowayJava_MW_ERROR_ALG_TYPE 40973L
#undef MowayJava_MW_ERROR_BIT_SIZE
#define MowayJava_MW_ERROR_BIT_SIZE 40974L
#undef MowayJava_MW_ERROR_FILE_TYPE
#define MowayJava_MW_ERROR_FILE_TYPE 40975L
#undef MowayJava_MW_ERROR_NO_INIT_PID
#define MowayJava_MW_ERROR_NO_INIT_PID 40976L
#undef MowayJava_MW_ERROR_NO_INIT_PIN
#define MowayJava_MW_ERROR_NO_INIT_PIN 40977L
#undef MowayJava_MW_ERROR_NO_VALIDATE_PKG
#define MowayJava_MW_ERROR_NO_VALIDATE_PKG 40978L
#undef MowayJava_MW_ERROR_AUTH_STAGE
#define MowayJava_MW_ERROR_AUTH_STAGE 40979L
#undef MowayJava_MW_ERROR_FILE_PRIVILEGE
#define MowayJava_MW_ERROR_FILE_PRIVILEGE 40980L
#undef MowayJava_MW_ERROR_FILE_RANGE
#define MowayJava_MW_ERROR_FILE_RANGE 40981L
#undef MowayJava_MW_ERROR_KEY_FILE
#define MowayJava_MW_ERROR_KEY_FILE 40982L
#undef MowayJava_MW_ERROR_REQ_IDENTIFY
#define MowayJava_MW_ERROR_REQ_IDENTIFY 40983L
#undef MowayJava_MW_ERROR_INVALID_SEED
#define MowayJava_MW_ERROR_INVALID_SEED 40984L
#undef MowayJava_MW_ERROR_SEED_CHECK
#define MowayJava_MW_ERROR_SEED_CHECK 40985L
#undef MowayJava_MW_ERROR_UPDATE_HASH
#define MowayJava_MW_ERROR_UPDATE_HASH 40986L
#undef MowayJava_MW_ERROR_UPDATE_PID
#define MowayJava_MW_ERROR_UPDATE_PID 40987L
#undef MowayJava_MW_ERROR_UPDATE_INDEX
#define MowayJava_MW_ERROR_UPDATE_INDEX 40988L
#undef MowayJava_MW_ERROR_UPDATE_TIME
#define MowayJava_MW_ERROR_UPDATE_TIME 40989L
#undef MowayJava_MW_ERROR_UPDATE_SERIAL_NUM
#define MowayJava_MW_ERROR_UPDATE_SERIAL_NUM 40990L
#undef MowayJava_MW_ERROR_UPDATE_SN
#define MowayJava_MW_ERROR_UPDATE_SN 40991L
#undef MowayJava_MW_ERROR_UPDATE_ORDER
#define MowayJava_MW_ERROR_UPDATE_ORDER 40992L
#undef MowayJava_MW_ERROR_UPDATE_OPERATE
#define MowayJava_MW_ERROR_UPDATE_OPERATE 40993L
#undef MowayJava_MW_ERROR_KEY_TYPE
#define MowayJava_MW_ERROR_KEY_TYPE 40994L
#undef MowayJava_MW_ERROR_OTHER
#define MowayJava_MW_ERROR_OTHER 45055L
/*
 * Class:     MowayJava
 * Method:    mw_enum
 * Signature: ([LMW_DEVICE_INFO_CTX;I[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1enum
  (JNIEnv *, jclass, jobjectArray, jint, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_open
 * Signature: (LMW_DEVICE_INFO_CTX;I[J)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1open
  (JNIEnv *, jclass, jobject, jint, jlongArray);

/*
 * Class:     MowayJava
 * Method:    mw_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MowayJava
 * Method:    mw_verify_pin
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1verify_1pin
  (JNIEnv *, jclass, jlong, jbyte, jbyteArray);

/*
 * Class:     MowayJava
 * Method:    mw_change_pin
 * Signature: (JBS[B[B)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1change_1pin
  (JNIEnv *, jclass, jlong, jbyte, jshort, jbyteArray, jbyteArray);

/*
 * Class:     MowayJava
 * Method:    mw_set_pid
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1set_1pid
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     MowayJava
 * Method:    mw_control
 * Signature: (JB[BI[BI[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1control
  (JNIEnv *, jclass, jlong, jbyte, jbyteArray, jint, jbyteArray, jint, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_get_device_info
 * Signature: (JB[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1get_1device_1info
  (JNIEnv *, jclass, jlong, jbyte, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_get_device_all_info
 * Signature: (JLMW_DEVICE_ALL_ITEM_INFO;)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1get_1device_1all_1info
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     MowayJava
 * Method:    mw_get_device_status
 * Signature: (JLMW_DEVICE_STATUS_CTX;)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1get_1device_1status
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     MowayJava
 * Method:    mw_enum_file
 * Signature: (J[LMW_FILE_PROPERTY;I[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1enum_1file
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_create_file
 * Signature: (JLMW_FILE_PROPERTY;)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1create_1file
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     MowayJava
 * Method:    mw_read_file
 * Signature: (J[BII[B)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1read_1file
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     MowayJava
 * Method:    mw_write_file
 * Signature: (J[BII[B)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1write_1file
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     MowayJava
 * Method:    mw_delete_file
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1delete_1file
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     MowayJava
 * Method:    mw_get_file_property
 * Signature: (J[BLMW_FILE_PROPERTY;)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1get_1file_1property
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     MowayJava
 * Method:    mw_sym_encrypt
 * Signature: (J[BB[B[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1sym_1encrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_sym_decrypt
 * Signature: (J[BB[B[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1sym_1decrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_rsa_encrypt
 * Signature: (J[BB[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1rsa_1encrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_rsa_decrypt
 * Signature: (J[BB[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1rsa_1decrypt
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_signature
 * Signature: (J[BB[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1signature
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_verify_sign
 * Signature: (J[BB[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1verify_1sign
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     MowayJava
 * Method:    mw_hmac_calc
 * Signature: (J[B[BI[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1hmac_1calc
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_make_update_pkg
 * Signature: (JI[B[LMW_UPDADE_FILE_CTX;I[B[I)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1make_1update_1pkg
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jobjectArray, jint, jbyteArray, jintArray);

/*
 * Class:     MowayJava
 * Method:    mw_update
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1update
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     MowayJava
 * Method:    mw_restore_factory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_MowayJava_mw_1restore_1factory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MowayJava
 * Method:    mw_get_error_desc
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_MowayJava_mw_1get_1error_1desc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
